tests = [ {'description': 'PUSH => 0x01', # ********************************************* // left	# TESTS WRITTEN FOR NON-PULLUP
	'steps': [{'inputs': [('PINA', 0x01)], 'iterations': 2}],
	'expected': [('PORTB', 0x01)],
	},
	{'description': 'PUSH => 0x01',
	'steps': [{'inputs': [('PINA', 0x00)], 'iterations': 2}],
	'expected': [('PORTB', 0x01)],
	}, 
	{'description': 'PUSH => 0x02',
	'steps': [{'inputs': [('PINA', 0x01)], 'iterations': 2}],
	'expected': [('PORTB', 0x02)],
	},
	{'description': 'PUSH => 0x02',
	'steps': [{'inputs': [('PINA', 0x00)], 'iterations': 2}],
	'expected': [('PORTB', 0x02)],
	},
	{'description': 'PUSH => 0x04',
	'steps': [{'inputs': [('PINA', 0x01)], 'iterations': 2}],
	'expected': [('PORTB', 0x04)],
	},
	{'description': 'PUSH => 0x04',
	'steps': [{'inputs': [('PINA', 0x00)], 'iterations': 2}],
	'expected': [('PORTB', 0x04)],
	}, 
	{'description': 'PUSH => 0x08',
	'steps': [{'inputs': [('PINA', 0x01)], 'iterations': 2}],
	'expected': [('PORTB', 0x08)],
	},
	{'description': 'PUSH => 0x08',
	'steps': [{'inputs': [('PINA', 0x00)], 'iterations': 2}],
	'expected': [('PORTB', 0x08)],
	}, 
	{'description': 'PUSH => 0x10',
	'steps': [{'inputs': [('PINA', 0x01)], 'iterations': 2}],
	'expected': [('PORTB', 0x10)],
	},
	{'description': 'PUSH => 0x10',
	'steps': [{'inputs': [('PINA', 0x00)], 'iterations': 2}],
	'expected': [('PORTB', 0x10)],
	}, 
	{'description': 'PUSH => 0x20',
	'steps': [{'inputs': [('PINA', 0x01)], 'iterations': 2}],
	'expected': [('PORTB', 0x20)],
	},
	{'description': 'PUSH => 0x20',
	'steps': [{'inputs': [('PINA', 0x00)], 'iterations': 2}],
	'expected': [('PORTB', 0x20)],
	},
	{'description': 'PUSH => 0x10',	# ********************************************** // right
	'steps': [{'inputs': [('PINA', 0x01)], 'iterations': 2}],
	'expected': [('PORTB', 0x10)],
	},
	{'description': 'PUSH => 0x10',
	'steps': [{'inputs': [('PINA', 0x00)], 'iterations': 2}],
	'expected': [('PORTB', 0x10)],
	}, 
	{'description': 'PUSH => 0x08',
	'steps': [{'inputs': [('PINA', 0x01)], 'iterations': 2}],
	'expected': [('PORTB', 0x08)],
	},
	{'description': 'PUSH => 0x08',
	'steps': [{'inputs': [('PINA', 0x00)], 'iterations': 2}],
	'expected': [('PORTB', 0x08)],
	},
	{'description': 'PUSH => 0x04',
	'steps': [{'inputs': [('PINA', 0x01)], 'iterations': 2}],
	'expected': [('PORTB', 0x04)],
	},
	{'description': 'PUSH => 0x04',
	'steps': [{'inputs': [('PINA', 0x00)], 'iterations': 2}],
	'expected': [('PORTB', 0x04)],
	}, 
	{'description': 'PUSH => 0x02',
	'steps': [{'inputs': [('PINA', 0x01)], 'iterations': 2}],
	'expected': [('PORTB', 0x02)],
	},
	{'description': 'PUSH => 0x02',
	'steps': [{'inputs': [('PINA', 0x00)], 'iterations': 2}],
	'expected': [('PORTB', 0x02)],
	}, 
	{'description': 'PUSH => 0x01',
	'steps': [{'inputs': [('PINA', 0x01)], 'iterations': 2}],
	'expected': [('PORTB', 0x01)],
	},
	{'description': 'PUSH => 0x01',
	'steps': [{'inputs': [('PINA', 0x00)], 'iterations': 2}],
	'expected': [('PORTB', 0x01)],
	},
	{'description': 'PUSH => 0x00',
	'steps': [{'inputs': [('PINA', 0x01)], 'iterations': 2}],
	'expected': [('PORTB', 0x00)],
	},
	{'description': 'PUSH => 0x00',
	'steps': [{'inputs': [('PINA', 0x00)], 'iterations': 2}],
	'expected': [('PORTB', 0x00)],
	}, 
	{'description': 'PUSH => 0x01', # ********************************************* // left	# TESTS WRITTEN FOR NON-PULLUP
	'steps': [{'inputs': [('PINA', 0x01)], 'iterations': 2}],
	'expected': [('PORTB', 0x01)],
	},
	{'description': 'PUSH => 0x01',
	'steps': [{'inputs': [('PINA', 0x00)], 'iterations': 2}],
	'expected': [('PORTB', 0x01)],
	}, 
	]
watch = ['direction', 'PORTB', 'LED_STATE']
