tests = [ {'description': 'PUSH => 0x01', # ********************************************* // right
	'steps': [{'inputs': [('PINA', 0x01)], 'iterations': 2}],
	'expected': [('PORTB', 0x01)],
	},
	{'description': 'PUSH => 0x01',
	'steps': [{'inputs': [('PINA', 0x00)], 'iterations': 2}],
	'expected': [('PORTB', 0x01)],
	}, 
	{'description': 'PUSH => 0x03',
	'steps': [{'inputs': [('PINA', 0x01)], 'iterations': 2}],
	'expected': [('PORTB', 0x03)],
	},
	{'description': 'PUSH => 0x03',
	'steps': [{'inputs': [('PINA', 0x00)], 'iterations': 2}],
	'expected': [('PORTB', 0x03)],
	},
	{'description': 'PUSH => 0x07',
	'steps': [{'inputs': [('PINA', 0x01)], 'iterations': 2}],
	'expected': [('PORTB', 0x07)],
	},
	{'description': 'PUSH => 0x07',
	'steps': [{'inputs': [('PINA', 0x00)], 'iterations': 2}],
	'expected': [('PORTB', 0x07)],
	}, 
	{'description': 'PUSH => 0x0F',
	'steps': [{'inputs': [('PINA', 0x01)], 'iterations': 2}],
	'expected': [('PORTB', 0x0F)],
	},
	{'description': 'PUSH => 0x0F',
	'steps': [{'inputs': [('PINA', 0x00)], 'iterations': 2}],
	'expected': [('PORTB', 0x0F)],
	}, 
	{'description': 'PUSH => 0x1F',
	'steps': [{'inputs': [('PINA', 0x01)], 'iterations': 2}],
	'expected': [('PORTB', 0x1F)],
	},
	{'description': 'PUSH => 0x1F',
	'steps': [{'inputs': [('PINA', 0x00)], 'iterations': 2}],
	'expected': [('PORTB', 0x1F)],
	}, 
	{'description': 'PUSH => 0x2F',
	'steps': [{'inputs': [('PINA', 0x01)], 'iterations': 2}],
	'expected': [('PORTB', 0x3F)],
	},
	{'description': 'PUSH => 0x2F',
	'steps': [{'inputs': [('PINA', 0x00)], 'iterations': 2}],
	'expected': [('PORTB', 0x3F)],
	},
	{'description': 'PUSH => 0x00',
	'steps': [{'inputs': [('PINA', 0x01)], 'iterations': 2}],
	'expected': [('PORTB', 0x00)],
	},
	{'description': 'PUSH => 0x00',
	'steps': [{'inputs': [('PINA', 0x00)], 'iterations': 2}],
	'expected': [('PORTB', 0x00)],
	}, 
	{'description': 'PUSH => 0x20',	# ********************************************** // right
	'steps': [{'inputs': [('PINA', 0x01)], 'iterations': 2}],
	'expected': [('PORTB', 0x20)],
	},
	{'description': 'PUSH => 0x20',
	'steps': [{'inputs': [('PINA', 0x00)], 'iterations': 2}],
	'expected': [('PORTB', 0x20)],
	}, 
	{'description': 'PUSH => 0x30',
	'steps': [{'inputs': [('PINA', 0x01)], 'iterations': 2}],
	'expected': [('PORTB', 0x30)],
	},
	{'description': 'PUSH => 0x30',
	'steps': [{'inputs': [('PINA', 0x00)], 'iterations': 2}],
	'expected': [('PORTB', 0x30)],
	},
	{'description': 'PUSH => 0x38',
	'steps': [{'inputs': [('PINA', 0x01)], 'iterations': 2}],
	'expected': [('PORTB', 0x38)],
	},
	{'description': 'PUSH => 0x38',
	'steps': [{'inputs': [('PINA', 0x00)], 'iterations': 2}],
	'expected': [('PORTB', 0x38)],
	}, 
	{'description': 'PUSH => 0x3C',
	'steps': [{'inputs': [('PINA', 0x01)], 'iterations': 2}],
	'expected': [('PORTB', 0x3C)],
	},
	{'description': 'PUSH => 0x3C',
	'steps': [{'inputs': [('PINA', 0x00)], 'iterations': 2}],
	'expected': [('PORTB', 0x3C)],
	}, 
	{'description': 'PUSH => 0x3E',
	'steps': [{'inputs': [('PINA', 0x01)], 'iterations': 2}],
	'expected': [('PORTB', 0x3E)],
	},
	{'description': 'PUSH => 0x3E',
	'steps': [{'inputs': [('PINA', 0x00)], 'iterations': 2}],
	'expected': [('PORTB', 0x3E)],
	}, 
	{'description': 'PUSH => 0x3F',
	'steps': [{'inputs': [('PINA', 0x01)], 'iterations': 2}],
	'expected': [('PORTB', 0x3F)],
	},
	{'description': 'PUSH => 0x3F',
	'steps': [{'inputs': [('PINA', 0x00)], 'iterations': 2}],
	'expected': [('PORTB', 0x3F)],
	},
	{'description': 'PUSH => 0x00',
	'steps': [{'inputs': [('PINA', 0x01)], 'iterations': 2}],
	'expected': [('PORTB', 0x00)],
	},
	{'description': 'PUSH => 0x00',
	'steps': [{'inputs': [('PINA', 0x00)], 'iterations': 2}],
	'expected': [('PORTB', 0x00)],
	}, 
	]
watch = ['direction', 'PORTB', 'LED_STATE']
