tests = [ {'description': 'Full Fuel',	# TESTS WRITTEN FOR NON-PULLUP
	'steps': [ {'inputs': [('PINA', 0x0F)], 'iterations': 2 } ],
	'expected': [('PORTC', 0x3F)],
	},
	{'description': '14 Fuel',
	'steps': [ {'inputs': [('PINA', 0x0E)], 'iterations': 2 } ],
	'expected': [('PORTC', 0x3F)],
	},
	{'description': '12 Fuel',
	'steps': [ {'inputs': [('PINA', 0x0C)], 'iterations': 2 } ],
	'expected': [('PORTC', 0x3E)],
	},
	{'description': '9 Fuel',
	'steps': [ {'inputs': [('PINA', 0x09)], 'iterations': 2 } ],
	'expected': [('PORTC', 0x3C)],
	},
	{'description': '8 Fuel',
	'steps': [ {'inputs': [('PINA', 0x08)], 'iterations': 2 } ],
	'expected': [('PORTC', 0x3C)],
	},
	{'description': '5 Fuel',
	'steps': [ {'inputs': [('PINA', 0x05)], 'iterations': 2 } ],
	'expected': [('PORTC', 0x38)],
	},
	{'description': '4 Fuel (Low Fuel)',
	'steps': [ {'inputs': [('PINA', 0x04)], 'iterations': 2 } ],
	'expected': [('PORTC', 0x70)],
	},
	{'description': '3 Fuel (Low Fuel)',
	'steps': [ {'inputs': [('PINA', 0x03)], 'iterations': 2 } ],
	'expected': [('PORTC', 0x70)],
	},
	{'description': '1 Fuel (Low Fuel)',
	'steps': [ {'inputs': [('PINA', 0x01)], 'iterations': 2 } ],
	'expected': [('PORTC', 0x60)],
	},
	{'description': 'No Fuel (Low Fuel)',
	'steps': [ {'inputs': [('PINA', 0x00)], 'iterations': 2 } ],
	'expected': [('PORTC', 0x40)],
	},
	]
watch = ['PINA', 'led', 'PORTC']
